ig.module(
	'game.scriptcore'
)
.requires(
	'impact.entity'
)
.defines(function(){
	EntityScriptCore = ig.Entity.extend(
	{
		WonGame : "YOU HAVE WON THE GAME", 
		StartingGame : "STARTING GAME", 
		EndingGame : "ENDING GAME", 
		NewPhase : "STARTING NEW PHASE", 
		EndPhase : "ENDING PHASE", 
		NewCycle : "STARTING NEW CYCLE", 
		EndCycle : "ENDING CYCLE", 
		CyclesRemaining : "CYCLES REMAINING "/* number */, 
		Blank : "&nbsp;", 

		StartNewEvent : "STARTING NEW EVENT "/* event name */, 

		BossEnteredRoom : "SPAWNING BOSS "/* boss name */, 

		PlayerRespawnCivilian : /* name */" IS REBORN AS A Civilian", 
		PlayerStartTurn : /* name */" STARTING THEIR TURN", 
		PlayerEndTurn : /* name */" ENDING THEIR TURN", 
		PlayerAttackingEnemy : /* player */" ATTACKING ENEMY "/* enemy */, 
		PlayerAttackMissed : "ATTACK MISSED", 
		PlayerRetryAttack : "RETRYING ATTACK", 
		PlayerDamage1 : /* player */" TAKING "/* damage amount */, 
		PlayerDamage2 : " DAMAGE", 
		PlayerDoorLockedDown : "THE ROOM IS LOCKED DOWN", 
		PlayerMoveThroughDoor : "MOVING TO DOOR", 
		PlayerUnlockDoor : "UNLOCK DOOR", 
		PlayerScavenge : "SCAVENGING FOR ITEM "/* item */, 
		PlayerScavengeNoItems : "ROOM HAS NO ITEMS", 
		PlayerScavengeFullInventory : "INVENTORY IS FULL", 
		PlayerHeal : "YOU HEAL ARE HEALED BY "/* amount */, 
		PlayerHealAlreadyFull : "YOU ARE ALREADY AT FULL HEALTH", 
		PlayerConvertJunk : "YOU CONVERT JUNK INTO SOMETHING USABLE", 
		PlayerNeedJunk : "YOU NEED ATLEAST 2 JUNK", 
		PlayerUseItem : "USING ITEM "/* item */, 
		PlayerGiveItem : "GIVING ITEM "/* item */, 
		PlayerDestroyItem : "DESTROYING ITEM "/* item */, 
		PlayerIgnoreDamage : "THE DAMAGE IS IGNORED", 
		PlayerImmuneNeurotoxin : "IMMUNE TO NEUROTOXIN", 
		PlayerDeath : /* name */" HAS DIED", 

		ItemBaseName : "dupe", 
		ItemBaseDescription : "This is an item", 
		ItemBaseUse : "This item cannot be used", 
		ItemBaseCannotUse : "This item cannot be used", 

		ItemAirMaskName : "Air Mask", 
		ItemAirMaskDescription : "http://wiki.decompressiongame.com/index.php?title=Air_Mask", 
		ItemBackpackName : "Backpack", 
		ItemBackpackDescription : "http://wiki.decompressiongame.com/index.php?title=Backpack", 
		ItemBackpackUse : "You gain 1 inventory slot", 
		ItemBlueKeycardName : "Blue Keycard", 
		ItemBlueKeycardDescription : "http://wiki.decompressiongame.com/index.php?title=Blue_Key_Card", 
		ItemBlueKeycardUse : "You used Blue Keycard", 
		ItemBlueKeycardCannotUse : "This must be used in the starting area", 
		ItemExoSuitName : "Exo-Suit", 
		ItemExoSuitDescription : "http://wiki.decompressiongame.com/index.php?title=Exo-Suit", 
		ItemFriendlyDroneName : "Friendly Drone", 
		ItemFriendlyDroneDescription : "http://wiki.decompressiongame.com/index.php?title=Friendly_Drone", 
		ItemGreenKeycardName : "Blue Keycard", 
		ItemGreenKeycardDescription : "http://wiki.decompressiongame.com/index.php?title=Green_Key_Card", 
		ItemGreenKeycardUse : "You used Blue Keycard", 
		ItemGreenKeycardCannotUse : "This must be used in the starting area", 
		ItemHealthKitName : "Health Kit", 
		ItemHealthKitDescription : "http://wiki.decompressiongame.com/index.php?title=Health_Kit", 
		ItemHealthKitUse : "You gain 3 health", 
		ItemHealthKitCannotUse : "You are already at full health", 
		ItemModAName : "Mod A", 
		ItemModADescription : "http://wiki.decompressiongame.com/index.php?title=Mod_A", 
		ItemModBName : "Mod B", 
		ItemModBDescription : "http://wiki.decompressiongame.com/index.php?title=Mod_B", 
		ItemModCName : "Mod C", 
		ItemModCDescription : "http://wiki.decompressiongame.com/index.php?title=Mod_C", 
		ItemOverrideKeyName : "Override Key", 
		ItemOverrideKeyDescription : "http://wiki.decompressiongame.com/index.php?title=Override_Key", 
		ItemRedKeycardName : "Red Keycard", 
		ItemRedKeycardDescription : "http://wiki.decompressiongame.com/index.php?title=Red_Key_Card", 
		ItemRedKeycardUse : "You used Red Keycard", 
		ItemRedKeycardCannotUse : "This must be used in the starting area", 
		ItemReflexShieldName : "Reflex Shield", 
		ItemReflexShieldDescription : "http://wiki.decompressiongame.com/index.php?title=Reflex_Shield", 
		ItemReflexShieldUse : "The next incoming damage is negated", 
		ItemRepairKitName : "Repair Kit", 
		ItemRepairKitDescription : "http://wiki.decompressiongame.com/index.php?title=Repair_Kit", 
		ItemRepairKitUse : "You transform some junk into a usable item", 
		ItemReprogrammingHardwareName : "Reprogramming Hardware", 
		ItemReprogrammingHardwareDescription : "http://wiki.decompressiongame.com/index.php?title=Reprogramming_Hardware", 
		ItemReprogrammingHardwareUse : "The hardware searched for the nearest machine to reprogram", 
		ItemReprogrammingHardwareCannotUse : "Chould not find any enemies in the room", 
		ItemResourceDetectorName : "Resource Detector", 
		ItemResourceDetectorDescription : "http://wiki.decompressiongame.com/index.php?title=Resource_detector", 
		ItemResourceDetectorUse : "This room's items have been refreshed", 
		ItemResourceDetectorCannotUse : "This room has no items", 
		ItemSmallSnackName : "Small Snack", 
		ItemSmallSnackDescription : "http://wiki.decompressiongame.com/index.php?title=Small_Snack", 
		ItemSmallSnackUse : "You gain 2 health", 
		ItemSmallSnackCannotUse : "You are already at full health", 
		ItemSubstanceXName : "Substance X", 
		ItemSubstanceXDescription : "http://wiki.decompressiongame.com/index.php?title=Substance_X", 
		ItemSubstanceXUse : "You are restored to full health", 
		ItemSubstanceXCannotUse : "You are already at full health", 
		ItemSystemResetName : "System Reset", 
		ItemSystemResetDescription : "http://wiki.decompressiongame.com/index.php?title=System_Reset", 
		ItemSystemResetUse : "The current event is disabled", 
		ItemWaterName : "Water", 
		ItemWaterDescription : "http://wiki.decompressiongame.com/index.php?title=Water", 
		ItemWaterUse : "You gain 1 health", 
		ItemWaterCannotUse : "You are already at full health", 

		ItemSensorImplantName : "Sensor Implant", 
		ItemSensorImplantDescription : "http://wiki.decompressiongame.com/index.php?title=Sensor_Implant", 
		ItemCommandImplantName : "Command Implant", 
		ItemCommandImplantDescription : "http://wiki.decompressiongame.com/index.php?title=Command_Implant", 
		ItemReflexImplantName : "Reflex Implant", 
		ItemReflexImplantDescription : "http://wiki.decompressiongame.com/index.php?title=Reflex_Implant", 
		ItemQuantumImplantName : "Quantum Implant", 
		ItemQuantumImplantDescription : "http://wiki.decompressiongame.com/index.php?title=Quantum_Implant", 
		ItemDiscoveryImplantName : "Discovery Implant", 
		ItemDiscoveryImplantDescription : "http://wiki.decompressiongame.com/index.php?title=Discovery_Implant", 
		ItemDefenseImplantName : "Defense Implant", 
		ItemDefenseImplantDescription : "http://wiki.decompressiongame.com/index.php?title=Defense_Implant", 

		ItemTeleporterName : 'Teleporter',
		ItemTeleporterDescription : 'http://wiki.decompressiongame.com/index.php?title=Teleporter',
		ItemShortCircuitActivate : 'Short Circuit',
		ItemShortCircuitDescription : 'http://wiki.decompressiongame.com/index.php?title=Short_Circuit',
		ItemLaserTripWireActivate : 'Laser Trip Wire',
		ItemLaserTripWireDescription : 'http://wiki.decompressiongame.com/index.php?title=Laser_Trip_Wire',
		ItemTheyAwakenActivate : 'They Awaken...',
		ItemTheyAwakenDescription : 'http://wiki.decompressiongame.com/index.php?title=They_Awaken...',

		ItemJunkName01 : 'A Potted Plant',
		ItemJunkDescription01 : 'http://wiki.decompressiongame.com/index.php?title=Potted_Plant',
		ItemJunkName02 : 'Empty Bottle',
		ItemJunkDescription02 : 'http://wiki.decompressiongame.com/index.php?title=Empty_Bottle',
		ItemJunkName03 : 'Broken Keycard', 
		ItemJunkDescription03 : 'http://wiki.decompressiongame.com/index.php?title=Broken_Key_card',
		ItemJunkName04 : 'Wasted Ammo', 
		ItemJunkDescription04 : 'http://wiki.decompressiongame.com/index.php?title=Wasted_Ammo',
		ItemJunkName05 : 'Scrap Parts',
		ItemJunkDescription05 : 'http://wiki.decompressiongame.com/index.php?title=Scrap_Parts',
		ItemJunkName06 : 'Empty Cardboard Box', 
		ItemJunkDescription06 : 'http://wiki.decompressiongame.com/index.php?title=Empty_Box',
		ItemJunkName07 : 'Video Game', 
		ItemJunkDescription07 : 'http://wiki.decompressiongame.com/index.php?title=Video_Game',
		ItemJunkName08 : 'Powerless Cell Phone', 
		ItemJunkDescription08 : 'http://wiki.decompressiongame.com/index.php?title=Powerless_Cell_Phone',
		ItemJunkName09 : 'Trashed Paperwork', 
		ItemJunkDescription09 : 'http://wiki.decompressiongame.com/index.php?title=Trashed_Paperwork',
		ItemJunkName10 : 'Power Cord', 
		ItemJunkDescription10 : 'http://wiki.decompressiongame.com/index.php?title=Power_Cord',

		DoorDescription : "http://wiki.decompressiongame.com/index.php?title=Valor", 

		EnemyAttackingPlayer : /* enemy */" ATTACKING "/* player */, 
		EnemyAttackMissed : "ATTACK MISSED", 
		EnemyDeath : /* enemy */" DESTROYED", 
		EnemySpawningOther : /* spawner */" SPAWNS A "/* spawned */, 

		ModOfBionicZombiesName : "Mod of Bionic Zombies", 
		ModOfBionicZombiesDescription : "http://wiki.decompressiongame.com/index.php?title=Mob_of_Bionic_zombies", 
		PSIAssassinName : "PSI Assassin", 
		PSIAssassinDescription : "http://wiki.decompressiongame.com/index.php?title=PSI_Assassin", 
		HackerName : "Hacker", 
		HackerDescription : "http://wiki.decompressiongame.com/index.php?title=Hacker", 
		HackerSpawnInRoom : /* name */" HAS SPAWNED AN EMEMY IN "/* room */, 
		HackerLockDoors : /* name */" HAS LOCKED ALL DOORS", 
		TycheName : "Tyche", 
		TycheDescription : "http://wiki.decompressiongame.com/index.php?title=Tyche", 
		TycheSpawnInRoom : /* name */" HAS SPAWNED AN EMEMY IN "/* room */, 
		TycheDamageAllPlayers : /* name */"DAMAGING ALL PLAYERS", 
		TycheDoesNothing : /* name */" DOES NOTHING", 
		TycheHealsPlayers : "ALL PLAYERS ARE HEALED BY 1 HITPOINT", 
		TycheGivesKeycard : /* player */" RECIEVES A KEYCARD", 

		BionicZombieName : "Bionic Zombie", 
		BionicZombieDescription : "http://wiki.decompressiongame.com/index.php?title=Bionic_Zombie", 
		CleanserName : "Cleanser", 
		CleanserDescription : "http://wiki.decompressiongame.com/index.php?title=Cleanser", 
		SuicidalDroneName : "Suicidal Drone", 
		SuicidalDroneDescription : "http://wiki.decompressiongame.com/index.php?title=Suicidal_Drone", 
		SmallRoamerName : "Small Roamer", 
		SmallRoamerDescription : "http://wiki.decompressiongame.com/index.php?title=Small_Roamer", 
		SecurityDroidName : "Security Droid", 
		SecurityDroidDescription : "http://wiki.decompressiongame.com/index.php?title=Security_Droid", 
		PlanetsideMinerName : "Planetside Miner", 
		PlanetsideMinerDescription : "http://wiki.decompressiongame.com/index.php?title=Planet-side_Miner", 
		RampantWalkerName : "Rampant Walker", 
		RampantWalkerDescription : "http://wiki.decompressiongame.com/index.php?title=Rampant_Walker", 
		PeaceWatcherName : "PeaceWatcher", 
		PeaceWatcherDescription : "http://wiki.decompressiongame.com/index.php?title=Peace_Watcher", 
		CorruptedScoutName : "Corrupted Scout", 
		CorruptedScoutDescription : "http://wiki.decompressiongame.com/index.php?title=Corrupter_Scout", 
		NavGuideName : "NavGuide", 
		NavGuideDescription : "http://wiki.decompressiongame.com/index.php?title=Nav-Guide", 
		NanoBotsName : "NanoBots", 
		NanoBotsDescription : "http://wiki.decompressiongame.com/index.php?title=Nanobots", 
		SmallMediBotName : "MediBot", 
		SmallMediBotDescription : "http://wiki.decompressiongame.com/index.php?title=Medibot", 
		CrewAutotronName : "Crew Autotron", 
		CrewAutotronDescription : "http://wiki.decompressiongame.com/index.php?title=Crew_Auto-tron", 

		init : function()
		{
			//console.log('INIT SCRIPTCORE');
		}, 
	});
});